CREATE TABLE jobs (
    job_id UUID PRIMARY KEY,
    status VARCHAR(100) NOT NULL,
    duration INTEGER NOT NULL,
    result TEXT,
    error TEXT,
    started_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
